.github/workflows/test.yml

create test action yaml

---

.github/workflows/test.yml
README.md

add codecov to action and badge to readme

---

.changie.yaml
changes/unreleased/Changed-20201227-000123.yaml

issue already resolved, adding change file and changie settings

---

.github/workflows/test.yml
changes/unreleased/Fixed-20201227-162645.yaml
cmd/init.go

fix directory permissions on unreleased folder

---

.github/workflows/test.yml
.golangci.yml
README.md
Taskfile.yml
cmd/batch.go
cmd/batch_test.go
cmd/change.go
cmd/change_test.go
cmd/cmd_suite_test.go
cmd/config.go
cmd/config_test.go
cmd/e2e_test.go
cmd/init.go
cmd/init_test.go
cmd/latest.go
cmd/merge.go
cmd/merge_test.go
cmd/new.go
cmd/new_test.go
cmd/utils.go
cmd/utils_test.go
main.go

add linting and some tests for 100% coverage

---

.changie.yaml
README.md
changes/unreleased/Changed-20201227-165034.yaml
cmd/config.go
cmd/config_test.go
cmd/new.go
cmd/new_test.go

use array of custom choices instead of map

---

README.md

add goreport card to readme

---

changes/unreleased/Fixed-20210101-142311.yaml
cmd/latest.go
cmd/latest_test.go

fix latest panicking when no releases exist

---

.github/workflows/test.yml
CHANGELOG.md
changes/header.tpl.md
website/config.toml
website/content/guide/changelog/index.md

Include changelog in website using a sneaky awk + append

---

.github/workflows/test.yml
cmd/e2e_test.go
cmd/gen.go
cmd/gen_test.go
go.sum
website/config.toml
website/content/cli/.gitignore
website/content/cli/_index.md

add hidden gen command for CLI docs

---

.github/workflows/test.yml

use changie.dev as website address

---

CONTRIBUTING.md
README.md

update readme from github guide

---

website/content/_index.md

Add additional information on website home page

---

.github/workflows/release.yml
.github/workflows/test.yml

publish docs only on new releases

---

.goreleaser.yml
changes/unreleased/Fixed-20210213-232202.yaml
changes/unreleased/Fixed-20210213-232319.yaml

Also update homepage to new website
Closes #48

Add maintainer to deb/rpm builds

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Closes #65
*  Update contributing guide
* Re-add bug report template that was deleted on accident

Add pull request template

---

.github/workflows/build-docs.yml
.github/workflows/codeql-analysis.yml
.github/workflows/test.yml

* do not run go test when no go files changed
* create a hugo build if appropriate files change
* run go analysis when go files change
Also test that the vercel bot is working :smirk:

split test workflow and only run on appropriate file changes

---

changes/unreleased/Added-20210509-202843.yaml
cmd/e2e_test.go
cmd/next.go
cmd/next_test.go

Next command

---

changes/unreleased/Added-20210624-011747.yaml
changes/unreleased/Changed-20210624-011850.yaml
changes/unreleased/Changed-20210624-011929.yaml
cmd/batch.go
cmd/batch_test.go
cmd/change.go
cmd/change_test.go
cmd/config.go
cmd/config_test.go
cmd/e2e_test.go
cmd/init.go
cmd/merge.go
cmd/new.go
cmd/new_test.go
website/content/config/formatting/index.md
website/content/guide/quick-start/index.md

Closes #116 
Still working on docs and change files

add extra component layer and make kinds optional

---

.changie.yaml
Taskfile.yml
changes/unreleased/Changed-20210703-173549.yaml
cmd/batch.go
cmd/batch_test.go
cmd/init.go
cmd/init_test.go
cmd/latest_test.go
cmd/merge_test.go
cmd/new_test.go
cmd/next_test.go
core/change.go
core/change_test.go
core/config.go
core/config_test.go
core/templatecache.go
core/templatecache_test.go
testutils/matchers.go
testutils/mocks.go
website/content/config/choices/index.md
website/content/config/kind-formatting/index.md
website/content/config/replacements/index.md
website/content/config/shared-formatting/index.md
website/content/guide/upgrade/index.md

Per kind configuration

---

.goreleaser.yml

Add github discussion config for goreleaser

---

.golangci.yml
changes/unreleased/Added-20210710-125348.yaml
cmd/batch.go
cmd/batch_test.go
core/config.go
website/content/config/directories/index.md
website/content/config/kind-formatting/index.md

Change format config per kind

---

website/content/guide/upgrade/index.md

Add upgrade guide summary for docs

---

changes/unreleased/Added-20210710-152254.yaml
changes/unreleased/Added-20210710-152306.yaml
changes/unreleased/Added-20210710-152402.yaml
core/change.go
core/change_test.go
core/config.go
website/content/config/directories/index.md
website/content/config/kind-formatting/index.md
website/content/config/replacements/index.md
website/content/config/shared-formatting/index.md

Closes #136
Kind options to skip body, skip global choices and our own additional choices.

Add kind config options for choices

---

changes/unreleased/Changed-20210710-231132.yaml
cmd/e2e_test.go
cmd/init.go

Remove starting newline for kind format

---

.github/workflows/test.yml
changes/unreleased/Added-20210711-152428.yaml
changes/unreleased/Added-20210711-152451.yaml
core/change.go
core/change_test.go
core/config.go
core/config_test.go
core/custom.go
core/custom_test.go
website/content/config/choices/index.md
website/content/config/shared-formatting/index.md

add min and max length options for strings and body configs

---

changes/unreleased/Added-20220111-204214.yaml
cmd/batch.go
cmd/batch_test.go

add keep parameter to batch command

---

.changes/unreleased/Added-20220123-151205.yaml
cmd/batch.go
cmd/batch_test.go
cmd/e2e_test.go

add dry-run flag to batch command

---

.changes/unreleased/Added-20220126-230301.yaml
Makefile
cmd/batch_test.go
cmd/e2e_test.go
cmd/new.go
cmd/new_test.go
core/change.go
core/change_test.go
shared/types.go

202 dry run new command

---

.changes/unreleased/Added-20220127-223128.yaml
cmd/e2e_test.go
cmd/merge.go
cmd/merge_test.go
testutils/mocks.go

add dry run option to merge command

---

.changes/unreleased/Added-20220209-215433.yaml
.changes/unreleased/Added-20220209-215619.yaml
.changes/unreleased/Deprecated-20220209-220909.yaml
cmd/batch.go
cmd/batch_test.go
cmd/e2e_test.go
core/config.go
core/config_test.go
testutils/mocks.go
website/content/config/directories/index.md
website/content/config/shared-formatting/index.md

Closes #222
Closes #225  
Closes #228 

refactor batch, add previous version to version header

---

.changes/unreleased/Changed-20220215-180245.yaml
cmd/batch_test.go
cmd/e2e_test.go
cmd/init.go
cmd/merge_test.go
core/config.go
core/utils_test.go

Remove exec bit

---

.changes/unreleased/Added-20220216-151511.yaml
.changes/unreleased/Added-20220216-151644.yaml
.changes/unreleased/Added-20220216-172131.yaml
.golangci.yml
cmd/batch.go
cmd/batch_test.go
core/config.go
core/config_test.go
core/templatecache.go
core/templatecache_test.go
go.mod
go.sum
website/content/config/directories/index.md
website/content/config/header-footer/index.md
website/content/config/shared-formatting/index.md

Closes #230
Closes #240 
@rocktavious ported from #233, will close the other one

allow for custom header and footer templates

---

.changes/unreleased/Changed-20220217-103154.yaml
cmd/batch_test.go
cmd/e2e_test.go
core/change.go
core/change_test.go
website/content/config/shared-formatting/index.md

change sort order for changes

---

.changes/unreleased/Added-20220220-154915.yaml
cmd/batch.go
cmd/batch_test.go
cmd/next.go
cmd/next_test.go
core/utils.go
core/utils_test.go

support prerelease and metadata for next and batch commands

---

.changes/unreleased/Added-20220220-214719.yaml
cmd/batch.go
cmd/batch_test.go
testutils/mocks.go

option to move unreleased files instead of keep or delete

---

.changes/unreleased/Added-20220221-144215.yaml
.github/PULL_REQUEST_TEMPLATE.md
cmd/batch.go
cmd/batch_test.go
core/utils.go
core/utils_test.go

249 include more dirs to search for changes

---

.changes/unreleased/Added-20220221-180550.yaml
cmd/batch.go
cmd/batch_test.go

add remove prerelease option to batch

---

.changes/unreleased/Fixed-20220315-105032.yaml
cmd/e2e_test.go
cmd/next.go
cmd/next_test.go

* fixes #284
Signed-off-by: Frederic BIDON <fredbi@yahoo.com>

fix-284-changie-next-v123

---

.changes/unreleased/Added-20220515-161120.yaml
cmd/new.go
cmd/new_test.go
core/change.go
core/change_test.go
core/config.go
core/config_test.go
website/content/config/shared-formatting/index.md

add option to customize filename for change fragments

---

.changes/unreleased/Added-20220515-164041.yaml
core/custom.go
core/custom_test.go
website/content/config/choices/index.md

Add optional flag for custom choices

---

.changes/unreleased/Added-20220515-172541.yaml
cmd/batch.go
cmd/merge.go
core/replacement.go
core/templatecache.go
website/content/config/header-footer/index.md
website/content/config/replacements/index.md
website/content/config/shared-formatting/index.md

Add version data to templates that have versions

---

.changes/unreleased/Added-20220529-001741.yaml
.changes/unreleased/Changed-20220617-232901.yaml
cmd/e2e_test.go
cmd/merge.go
cmd/merge_test.go
core/config.go

Make header path optional when merging a changelog file

---

.changes/unreleased/Added-20220731-174813.yaml
.changes/unreleased/Added-20220731-174906.yaml
cmd/new.go
core/change.go
core/change_test.go
core/config.go
core/custom.go
core/custom_test.go

Hey, I added a few options to the `new` command. 
`make lint` was nagging about cyclomatic complexity in `AskPrompts` after the change, so I also refactored it a... little... in the second commit. Feel free to drop that one if you don't like it. :D
Adding close issues
Closes #338 
Closes #339

add `-k/--kind` and `-b/--body` options to new command

---

.changes/unreleased/Added-20220827-163810.yaml
cmd/new.go
core/change.go
core/change_test.go

add component option to new command

---

.changes/unreleased/Added-20220827-211241.yaml
core/change.go
core/change_test.go
core/config.go

new config for post processing

---

docs/content/guide/installation/index.md

Closes #398
Closes #397 
My first contribution to this project

Docker Guide -- fix installation and usage

---

.github/dependabot.yml

set dependabot to update weekly

---

.changes/unreleased/Fixed-20221203-000348.yaml
cmd/init.go
cmd/init_test.go
core/config.go
core/config_test.go
core/custom.go
core/replacement.go
shared/types.go

init should not override existing configs

---

.changes/unreleased/Fixed-20221209-193225.yaml
cmd/batch.go
cmd/batch_test.go

* add force option to batch to skip the above check
Closes #406

batch should not override an existing version file

---

core/config.go

Update docs to use correct case in example

---

docs/themes/hugo-whisper-theme/assets/js/libs/library.js
docs/themes/hugo-whisper-theme/assets/js/pages/services.js
docs/themes/hugo-whisper-theme/layouts/partials/contribute-footer.html

fix edit page on changie.dev (website->docs)

---

docs/content/integrations/nodejs.md

Updates docs for replacements api

---

.github/workflows/changelog-check.yml
.github/workflows/test.yml
.golangci.yml

Closes #574
No change needed
/label "skip changelog"

fix linting by setting goconst min len to 5

---

.changes/unreleased/Added-20231213-231049.yaml
cmd/new.go
cmd/new_test.go
cmd/root.go

New command will create the unreleased folder if it does not already exist

---

.changes/unreleased/Added-20240115-130635.yaml
cmd/merge.go
cmd/merge_test.go
core/config.go

Closes #591
Will now drop the preview output for projects

Support per project replacements

---

.changes/unreleased/Removed-20240115-131239.yaml
.changie.yaml
cmd/batch.go
cmd/latest.go
cmd/new.go
cmd/next.go
core/prompt.go
core/templatecache.go

Closes #597
Projects should now be considered stable

Remove any preview warning about projects

---

.github/workflows/build-docs.yml
.github/workflows/test.yml

Run test checks when updating actions in tests

---

docs/integrations/goreleaser.md
docs/integrations/index.md
docs/integrations/nodejs.md
docs/integrations/release_trigger.md
docs/integrations/yq.md
mkdocs.yml

Closes #551
Just a small page for now

add yq docs

---

.changes/unreleased/added-20240907-165020.yaml
core/change.go
core/config.go
core/utils.go
core/utils_test.go

KindKey and KindLabel values to Change data to be used in formats

---

.changes/unreleased/fixed-20240912-000012.yaml
cmd/batch.go
cmd/batch_test.go

Closes #714 
Can add a test for this as well.  Still getting that piece to work properly.

cleanup versioned changelog file on template error

---

.changes/unreleased/fixed-20250322-154321.yaml
.github/workflows/build-docs.yml
.github/workflows/changelog-check.yml
.github/workflows/gen-release-pr.yml
.github/workflows/release.yml
.github/workflows/test.yml
.golangci.yml
Makefile
cmd/gen.go
cmd/gen_test.go
core/config.go
core/config_test.go
core/custom.go
core/prompt.go
core/utils_test.go
go.mod
then/basic.go
then/io.go

Closes #760
Just some test updates really, and some linting

Bump go to 1.24

---

.changes/unreleased/added-20250531-170947.yaml
cmd/e2e_test.go
cmd/new.go
cmd/new_test.go
core/prompt.go
core/prompt_test.go
then/write.go

Support disabling prompts for CI or if you disable it in the new command

---

.changes/unreleased/added-20250601-021334.yaml
cmd/diff.go
cmd/diff_test.go
cmd/latest.go
cmd/latest_test.go
cmd/root.go

Diff command
